version: "3.7"

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./sql/init:/docker-entrypoint-initdb.d
      - ./sql/data:/var/lib/mysql
      - ./sql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
