version: '3.7'
services:
    db:
        image: mysql:5.7
        ports:
            - "3306:3307"
        volumes:
            - ./db/init:/docker-entrypoint-initdb.d
            - ./db/data:/var/lib/mysql
            - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sample
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
